Fix: Duration TS type
tauri-apps/tauri-plugin-stronghold pull request #69
Opened 2022-03-07 22:42 UTC by pwltr

Small issue I came upon while building, Fairly sure this should match the Rust std::time::Duration trait.

https://github.com/rust-lang/rust/blob/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/time.rs#L72-L75

2022-03-08 00:12 UTC, lucasfernog commented on src/stronghold.rs
> +                    break;
the password clear interval can still be changed later, so we can't break here (unless we start the process again with a new thread).

2022-03-08 00:13 UTC, lucasfernog requested changes
the current solution might fix the issue but it causes a problem if the clear interval is initially 0 and later changed to a different value.

2022-03-08 00:45 UTC, pwltr commented
I see, well this may be over my head then. It works for my case for now. I will revisit this once I'm better at Rust :)

2022-04-11 14:02 UTC, pwltr commented
Updated PR to only include changes of initial fix (Duration type)

2022-12-18 16:22 UTC, JonasKruckenberg commented
See https://github.com/tauri-apps/plugins-workspace/pull/38

2022-12-18 16:22 UTC, closed without merging